### ISSUE TITLE
Can't write to csv

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-Output-Biomass-Community#1]
The extension installs and the core recognizes it now, but it can't write the data to the csv.

2017-10-20 07:04:32,839 - Loading Output Biomass Community extension ...
2017-10-20 07:04:32,878 - Running Output Biomass Community ...
2017-10-20 07:04:32,880 -    Opening community log file "output-community/community-input-file-0.csv" ...
2017-10-20 07:04:32,883 - Could not find a part of the path 'D:\LANDIS runs\VIFF_Runs\Single_Cell\Aspen-Calibrate\output-community\community-input-file-0.csv'.

**Comment by rmscheller** [comment]
Fixed, not tested.  New installer ready.

**Comment by mslucash** [comment]
Same problem remains.  

2017-10-21 07:19:01,152 -    Opening a NECN_Hydro log file "NECN_Hydro-prob-establish-log.csv" ...
2017-10-21 07:19:01,212 - Loading Output Biomass Community extension ...
2017-10-21 07:19:01,242 - Running Output Biomass Community ...
2017-10-21 07:19:01,244 -    Opening community log file "output-community\community-input-file-0.csv" ...
2017-10-21 07:19:01,244 - Could not find a part of the path 'D:\LANDIS runs\VIFF_Runs\Single_Cell\Aspen-Calibrate\output-community\community-input-file-0.csv'.
@rmscheller

**Comment by rmscheller** [comment]
I got rid of the sub-directory.  New installer.

**Comment by mslucash** [comment]
There's no installer up there. Not even the old one so I can recompile. @rmscheller

**Comment by rmscheller** [comment]
ISS tool giving me fits this morning.  New installer.

**Comment by mslucash** [comment]
OK, it runs now!!!  It spits out a file for each timestep, but it looks like it's not writing out the map codes properly (see attached file).

I started with this as a single cell and the attached file is the output from time step =0.  So it should have a map code 3 in the attached file.
MapCode    3 <<this is my new IC community
 QuakingAspen 10 (42) 20 (130)
 
Also, I thought the plan was to spit out a txt file more like a spreadsheet that would make it easier to read into R.  Like column for map code, one for species, one for age, one for biomass.  Too hard to code?  

![error_filewriting_102117](https://user-images.githubusercontent.com/7819936/31853538-e74377a2-b63e-11e7-8cfd-f1cd7ccbdb57.JPG)
